### ISSUE TITLE
Could open the source codes as soon as possible? Thank you!

### ISSUE THREAD

**Issue by FlyingCat-fa** [kaishxu/DFMed#1]
I am very interested in your work. May I kindly inquire if it would be possible to the open source codes as soon as possible? Thank you.

**Comment by kaishxu** [comment]
I will release it soon! Thanks for your attention!

**Comment by kaishxu** [comment]
Released! Thank you!

**Comment by kaishxu** [comment]
Released! Enjoy!

**Comment by FlyingCat-fa** [comment]
Thanks very much!
